src/ProjectObservatorio/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import  path,include
from django.conf.urls.static import static  
from django.conf.urls import url


from posts import views
from portal import views
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('portal.urls', 'portal'), namespace='portal')),
    path('accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/portal/urls.py
from django.urls import include, path

from portal import views

urlpatterns = [
    path('',views.inicio, name='inicio'),    
    path('contact',views.contacto, name='contact'),
    path('invite',views.invitacionAdmin, name='inviteadmin'),      
    path('solicitud_registro',views.solicitud_registro, name='solicitudregistro'),      

]

src/posts/urls.py
from django.urls import include, path

from posts import views

urlpatterns = [
    path('',views.post_list, name='list'),
    path('news_list_egresado',views.post_list_Egresado, name='listnewsegresado'),
    path('news_list',views.post_list_update, name='newslistupdate'),
    path('create_news/',views.post_create, name='create'),
    path('create_interes/',views.interes_create, name='createinteres'),
    path('<slug:slug>/',views.post_detail, name='detail'),
    path('edit/<int:id>',views.post_update, name="update"),
    # path('<slug:slug>/delete/',views.post_delete, name='delete'),
    path('delete/<int:id>',views.post_delete, name='delete'),

]

src/users/urls.py
from django.urls import include, path

from users import views

urlpatterns = [
    path('list_user',views.user_list, name='userlist'),     
    path('detail_user',views.user_detail, name='userdetail'),     
    path('find_friend',views.user_find_friend, name='userfindfriend'),     
    path('update_user',views.user_update, name='userupdate'),     
    path('update_interes',views.user_update_Interes, name='userupdateinteres'),     
    path('enable_admin_user',views.user_enable_admin, name='userenableadmin'),     
    path('<int:id>',views.user_enable_detail, name='userenabledetail'),     
    path('admin/<int:id>',views.user_enable_detail_admin, name='userenabledetailadmin'),     
    path('update_user_list',views.user_list_update, name='userlistupdate'),     
    path('update_user_observatorio/<int:id>',views.user_update_observatorio, name='userupdateobservatorio'), 
    path('update_user_observatorio/admin/<int:id>',views.user_Admin_update_observatorio, name='useradminupdateobservatorio'), 
    path('user_list_disable_admin',views.user_list_disable_admin, name='userlistdisableadmin'),     
    path('user_list_disable_egresado',views.user_list_disable_egresado, name='userlistdisableegresado'),     
    path('disable_user/<int:id>',views.user_disable, name='userdisable'),    
    path('disable_user/admin/<int:id>',views.user_admin_disable, name='useradmindisable'),    
    path('enable_egresado_user',views.user_enable_egresado, name='userenableegresado'),
]

src/posts/forms.py
from django import forms

from .models import Post, Interes

class InteresForm(forms.ModelForm):
    class Meta:
        model = Interes
        
        fields ={
            "nombre",
            "descripcion",
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('titulo', 'imagen', "contenido", "publish")    
        # widgets = {
        #      'categorias': forms.CheckboxSelectMultiple(),
        #  }
   
    categorias = forms.ModelMultipleChoiceField(queryset=Interes.objects.all())

    def __init__(self, *args, **kwargs):
        # Only in case we build the form from an instance
        # (otherwise, 'toppings' list should be empty)
        if kwargs.get('instance'):
            # We get the 'initial' keyword argument or initialize it
            # as a dict if it didn't exist.
            initial = kwargs.setdefault('initial', {})
            # The widget for a ModelMultipleChoiceField expects
            # a list of primary key for the selected data.
            initial['categorias'] = [t.pk for t in 
                kwargs['instance'].interes_set.all()]

        forms.ModelForm.__init__(self, *args, **kwargs)

    # Overriding save allows us to process the value of 'toppings' field
    def save(self, commit=True):
        # Get the unsaved Pizza instance
        instance = forms.ModelForm.save(self, False)

        # Prepare a 'save_m2m' method for the form,
        old_save_m2m = self.save_m2m

        def save_m2m():
            old_save_m2m()
            # This is where we actually link the pizza with toppings
            instance.categorias.clear()
            for interes in self.cleaned_data['categorias']:
                instance.categorias.add(interes)

        self.save_m2m = save_m2m

        # Do we need to save all changes now?
        #if commit:
        instance.save()
        self.save_m2m()

        return instance

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('titulo', 'imagen', "contenido", "publish")    
        # widgets = {
        #      'categorias': forms.CheckboxSelectMultiple(),
        #  }
   
    categorias = forms.ModelMultipleChoiceField(queryset=Interes.objects.all())

    def __init__(self, *args, **kwargs):
        # Only in case we build the form from an instance
        # (otherwise, 'toppings' list should be empty)
        if kwargs.get('instance'):
            # We get the 'initial' keyword argument or initialize it
            # as a dict if it didn't exist.
            initial = kwargs.setdefault('initial', {})
            # The widget for a ModelMultipleChoiceField expects
            # a list of primary key for the selected data.
            initial['categorias'] = [t.pk for t in 
                kwargs['instance'].categorias.all()]

        forms.ModelForm.__init__(self, *args, **kwargs)

    # Overriding save allows us to process the value of 'toppings' field
    def save(self, commit=True):
        # Get the unsaved Pizza instance
        instance = forms.ModelForm.save(self, False)

        # Prepare a 'save_m2m' method for the form,
        old_save_m2m = self.save_m2m

        def save_m2m():
            old_save_m2m()
            # This is where we actually link the pizza with toppings
            instance.categorias.clear()
            for interes in self.cleaned_data['categorias']:
                instance.categorias.add(interes)

        self.save_m2m = save_m2m

        # Do we need to save all changes now?
        #if commit:
        instance.save()
        self.save_m2m()

        return instance

src/posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator
from django.contrib.auth import authenticate
from django.utils import timezone
from functools import reduce
import operator
from operator import and_
from django.db.models import Q
from django.core.exceptions import PermissionDenied
# Create your views here.

from .forms import PostForm ,PostUpdateForm, InteresForm
from .models import Post, Interes #importo mi modelo


def post_create(request):
    if not request.user.Administrador :
        print("Bienvenido %s" %(request.user))
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance = form.save(commit = False)
        #print( form.cleaned_data.get("titulo"))
        instance.user = request.user
        instance.save()
        messages.success(request, "tu Noticia ha sido creado con exito")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {        
        "form": form,
    }
    if request.user.Administrador:
        return render(request,"post_form.html", context)
    else:
        raise PermissionDenied

def interes_create(request):
    if not request.user.Administrador :
        raise Http404

    form = InteresForm(request.POST or None, request.FILES or None)
    #if request.method == "POST":
    #print (request.POST.get("titulo"))
    if form.is_valid():
        instance = form.save(commit = False)
        #print( form.cleaned_data.get("titulo"))
        instance.user = request.user
        instance.save()
        messages.success(request, "Interes creado con exito")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {        
        "form": form,
    }
    if request.user.Administrador:
        return render(request,"interes_form.html", context)
    else:
        raise PermissionDenied

def post_detail(request, slug=None):
    #instance= Post.objects.get(id=None)
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.Administrador:
            raise Http404    
    share_string = quote_plus(instance.titulo)
    context = {        
        "title": instance.titulo,
        "instance": instance,
        "share_string":share_string,
    }
    if request.user.Administrador or request.user.Egresado:
        return render(request,"post_detail.html", context)
    else:
        raise PermissionDenied
    
def post_list(request):
    if not request.user.Administrador :
        raise Http404
    hoy = timezone.now().date()
    queryset = Post.objects.active()#filter(draft=False).filter(publish__lte= timezone.now())#all(),order_by("-timestamp")
    if request.user.Administrador and not request.user.is_superuser:
        queryset = Post.objects.all()
    query = request.GET.get("q")
    if query:
        queryset=queryset.filter(
            Q(titulo__icontains=query)|
            Q(categorias__nombre__icontains=query)|
            Q(contenido__icontains=query)|
            Q(user__first_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset, 2) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    objects_list = paginator.get_page(page_number)
    
    context = {
        "objects_list": objects_list,
        "title": "Listado Noticias", 
        "hoy": hoy,        
    }

    if request.user.Administrador:
        return render(request,"post_list.html", context)
    else:
        raise PermissionDenied

def post_list_Egresado(request):
    if not request.user.Egresado :
        raise Http404
    intereses =[]
    if request.user.Egresado:
        for i in request.user.categorias.all():
            intereses.append(i.nombre)

    hoy = timezone.now().date()
    queryset = Post.objects.active()#filter(draft=False).filter(publish__lte= timezone.now())#all(),order_by("-timestamp")
    if request.user.Egresado and not request.user.Administrador and not request.user.is_superuser:
        q = Q()
        for i in intereses:
            q |= Q(categorias__nombre__icontains = i)
        
    queryset = Post.objects.filter(q)
    query = request.GET.get("q")

    if query:
        queryset=queryset.filter(
            Q(titulo__icontains=query)|
            Q(categorias__nombre__icontains=query)|
            Q(contenido__icontains=query)|
            Q(user__first_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset, 2) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    objects_list = paginator.get_page(page_number)
    
    context = {
        "objects_list": objects_list,
        "title": "Listado Noticias Egresado", 
        "hoy": hoy,        
    }

    if request.user.Egresado:
        return render(request,"post_list.html", context)
    else:
        raise PermissionDenied

def post_list_update(request):
    hoy = timezone.now().date()
    queryset = Post.objects.active()#filter(draft=False).filter(publish__lte= timezone.now())#all(),order_by("-timestamp")
    if request.user.Administrador and not request.user.is_superuser:
        queryset = Post.objects.filter(user=request.user)
    query = request.GET.get("q")
    if query:
        queryset=queryset.filter(
            Q(titulo__icontains=query)|
            Q(categorias__nombre__icontains=query)|
            Q(contenido__icontains=query)|
            Q(user__first_name__icontains=query)
            ).distinct()
    paginator = Paginator(queryset, 2) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    objects_list = paginator.get_page(page_number)
    
    context = {
        "objects_list": objects_list,
        "title": "Listado Noticias", 
        "hoy": hoy,        
    }

    if request.user.Administrador:
        return render(request,"post_list_update.html", context)
    else:
        raise PermissionDenied

def post_update(request, id= None):
    Bandequery= 0
    if not request.user.Administrador :
        raise Http404
    instance = get_object_or_404(Post, id=id) 

    if request.user == instance.user:
        Bandequery= 1

    if Bandequery== 1:
        form = PostUpdateForm(request.POST or None, request.FILES or None, instance= instance)# edit el form
        if form.is_valid():
            instance = form.save(commit = False)
            instance.save()
            messages.success(request, "Tu Noticia ha sido modificada", extra_tags="html_safe")                
            return HttpResponseRedirect(instance.get_absolute_url())    

        context = {        
            "title": instance.titulo,
            "instance": instance,
            "form": form,
        }

    if Bandequery== 1:
        if request.user.Administrador:
            return render(request,"post_form_update.html", context)
        else:
            raise PermissionDenied
    else:
        raise PermissionDenied

def post_delete(request, id=None):
    Bandequery= 0
    if not request.user.Administrador:
        raise Http404
    instance = get_object_or_404(Post, id=id)

    if request.user == instance.user:
        Bandequery= 1

    if Bandequery== 1:
        instance.delete()
        messages.success(request, "tu post ha sido Eliminado")

    if Bandequery== 1:
        if request.user.Administrador:
            return redirect("posts:list")
        else:
            raise PermissionDenied
    else:
        raise PermissionDenied
    
# def post_update(request, slug= None):
#     if not request.user.Administrador :
#         raise Http404
#     instance = get_object_or_404(Post, slug=slug) 

#     form = PostForm(request.POST or None, request.FILES or None, instance= instance)# edit el form
#     if form.is_valid():
#         instance = form.save(commit = False)
#         instance.save()
#         messages.success(request, "tu <a href='#'> post </a> ha sido modificado", extra_tags="html_safe")                
#         return HttpResponseRedirect(instance.get_absolute_url())    

#     context = {        
#         "title": instance.titulo,
#         "instance": instance,
#         "form": form,
#     }
#     if request.user.Administrador:
#         return render(request,"post_form.html", context)
#     else:
#         raise PermissionDenied

src/templates/contacto.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Contacto | {{block.super}}{% endblock %}

{% block content %}

    <div class="col-sm-10 col-sm-offset-1">
        {% if titulo %}
        <!-- <h1 class="text-align-center"><strong>{{ titulo }}</strong></h1> -->
        {% endif %}
        
        <form method="POST" action="{% url 'portal:contact' %}">{% csrf_token %}
            {{ form_contacto|crispy }}
            <b></b>
            <p class="text-center"><input class="btn btn-primary" type="submit" value="Enviar"/>
            <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
        </form>
    </div>

{% endblock %}

src/templates/headsidebar2.html
{% load static %}
</table-here>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

src/templates/inviteadmin.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Invitar Administrador| {{block.super}}{% endblock %}

{% block content %}

    <div class="col-sm-10 col-sm-offset-1">
        {% if titulo %}
        <!-- <h2 class="text-align-center"><strong>{{ titulo }}</strong></h2> -->
        {% endif %}
        
        <form method="POST" action="{% url 'portal:inviteadmin' %}">{% csrf_token %}
            {{ form_contacto|crispy }}
            <br/>
            <p class="text-center"><input class="btn btn-primary" type="submit" value="Invitar"/>
                <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a></p>
            
        </form>
    </div>

{% endblock %}

src/templates/javascript.html
{% load static %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    

src/templates/navbar.html
{% load static %}
<!-- Static navbar -->
<nav  class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Observatorio Egresados</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >
        <img src='{% static "img/logoUTP.jpg" %}' class="img-responsive" width="100" height="100" style="width:110%;">
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li class="active"><a href="{% url 'portal:inicio' %}">Inicio</a></li>
        {% if request.user.is_authenticated  %}
            <li><a href="{% url 'users:userdetail' %}">   Ver Perfil</a></li>
        {% endif %}

        {% if request.user.Administrador or request.user.Egresado and not user.is_superuser %}
        <!-- <li><a href="{% url 'users:userlist' %}">   Ver Perfil</a></li> -->
        <li class="active"><a href="{% url 'portal:contact' %}">   Contacto</a></li>
        {% endif %}
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul> -->
      </ul>
        <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li class="active"><a href="{% url 'auth_logout' %}">Cerrar Sesion</a></li>
        <!-- <li><a href="{% url 'registration_register' %}">Registrarte</a></li>   -->
        <!-- <li class="active"><a href="{% url 'auth_login' %}">Login</a></li> -->
        {% endif %}
        </ul>

      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
          <form class="navbar-form navbar-right" method="POST" action="{% url 'auth_login' %}">{% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name="username" placeholder="Usuario"/>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" name="password" placeholder="Clave"/>
            </div>
            <button type="submit" class="btn btn-default">Iniciar Sesion</button>
          </form>
      {% else %}
          {% if not user.is_superuser and request.user.Administrador%}
              <center><h3 style="margin: 12px"><span class="label label-default">Administrador | {{request.user }}</h3></span></center>
          {% endif %}
          {% if  user.is_superuser %} 
              <center><h3 style="margin: 12px"><span class="label label-default">Superusuario | {{request.user }}</h3></span></center>
          {% endif %}
          {% if  user.Egresado %} 
              <center><h3 style="margin: 12px"><span class="label label-default">Usuario | {{request.user }}</h3></span></center>
          {% endif %}
      {% endif %}
    </div><!--/.nav-collapse -->
  </div>
</nav>

src/templates/post_form_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title%}Crear Noticia | {{ block.super }} {% endblock %}

{% block content %}
<div class="col-sm-10 col-sm-offset-1" >
<!-- <h2><center><strong>Crear Noticia</strong> </center></h2> -->
    <form method="POST" action="" enctype="multipart/form-data" >{% csrf_token %}
        {{ form|crispy }}
        <br/>
        <p class="text-center"><input class="btn btn-primary" type="submit" value="Guardar Cambios">
        <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
    </form>
</div>
{% endblock %}

src/templates/solicitud_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Solicitud Registro | {{block.super}}{% endblock %}

{% block contentOut %}

    <div class="col-sm-6 col-sm-offset-3">
            {% if not user.is_authenticated %}
            <center><h2><strong>{{ titulo }}</strong></h2></center>    
                <form method="POST" action="">{% csrf_token %}
                {{ form_register | crispy }}
                <input class='btn btn-primary' type='submit' value='Enviar Solicitud' />
            </form>
            {% endif %}
    </div>

{% endblock %}

src/templates/user_list_update.html
{% extends "base.html" %}
    {% block head_title%}Modificar Usuario | {{ block.super }} {% endblock %}

{% block content %}
<div class="col-sm-10 col-sm-offset-1">
    <!-- <h2><strong><center>{{ title }}</center></strong></h2> -->
    <center>
    <form method="GET" action="">
        <input class="text-align-center" type="text" name="q" placeholder="Buscar Usuario" value="{{ request.GET.q }}"/>
        <input type="submit" value="Buscar" />
    </form>
    </center>
    <!-- {{ objects_list }} <br/> -->
    <br>

{% if user.is_superuser %}
    {% for obj in objects_list %}
        {% if obj.Administrador %}
                  <div class="col">
                      
                    <div class="panel-body">
                      <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                        {% if not obj.imagen_Perfil %}
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
                        {% else %}
                            <img src="{{ obj.imagen_Perfil.url }}" class="img-circle img-responsive"/>
                        {% endif %}
                        
                        {% if obj.biografia %}
                        <h4><strong>Biografia</strong></h4> 
                        <p>{{ obj.biografia }}</p>
                        {% endif %}
                 
                      </div>
                      <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
                          <div class="container" >
                            <h2><strong>{{ obj.username }}</strong></h2>
                            <p>Cargo: <b> {% if obj.is_superuser %} Superusuario {% endif %}{% if obj.Administrador %}Administrador {% endif %}</b></p>
                          
                           
                          </div>
                           <hr>
                          <ul class="container details" >
                            <li><p><span class="glyphicon glyphicon-user one" style="width:50px;"></span>{% if obj.get_full_name %}{{ obj.get_full_name }} {% else %}{{ obj.username }} {% endif %}</p></li>
                            <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>{{ obj.email }}</p></li>
                            {% if obj.telefono %}<li><p><span class="glyphicon glyphicon-phone" style="width:50px;"></span>{{ obj.telefono }}</p></li>{% endif %}
                            {% if obj.ciudad %}<li><p><span class="glyphicon glyphicon-globe" style="width:50px;"></span>{{ obj.ciudad }}</p></li>{% endif %}
                          </ul>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >{% if obj.fecha_Nacimiento %}Fecha de Nacimiento: {{ obj.fecha_Nacimiento }}{% endif %}</div>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >Se unió: {{ obj.date_joined }}</div>
                          
                      </div>
                    </div>
                    <hr>
                    <p class="text-center"><a href="{% url 'users:useradminupdateobservatorio' id=obj.id %}" class="btn btn-primary" role="button">Modificar Datos Administrador</a>
                    <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
                </div>
        {% endif %}
    {% endfor %}
{% endif %}

{% if user.Administrador and not user.is_superuser %}
    {% for obj in objects_list %}
        {% if obj.Egresado %}
                  <div class="col">
                      
                    <div class="panel-body">
                      <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                        {% if not obj.imagen_Perfil %}
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive"> 
                        {% else %}
                            <img src="{{ obj.imagen_Perfil.url }}" class="img-circle img-responsive"/>
                        {% endif %}
                        
                        {% if obj.biografia %}
                        <h4><strong>Biografia</strong></h4> 
                        <p>{{ obj.biografia }}</p>
                        {% endif %}
                 
                      </div>
                      <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8" >
                          <div class="container" >
                            <h2><strong>{{ obj.username }}</strong></h2>
                            <p>Cargo: <b> {% if obj.is_superuser %} Superusuario {% endif %}{% if obj.Administrador %}Administrador {% endif %}{% if obj.Egresado %}Usuario {% endif %}</b></p>
                          
                           
                          </div>
                           <hr>
                          <ul class="container details" >
                            <li><p><span class="glyphicon glyphicon-user one" style="width:50px;"></span>{% if obj.get_full_name %}{{ obj.get_full_name }} {% else %}{{ obj.username }} {% endif %}</p></li>
                            <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>{{ obj.email }}</p></li>
                            {% if obj.telefono %}<li><p><span class="glyphicon glyphicon-phone" style="width:50px;"></span>{{ obj.telefono }}</p></li>{% endif %}
                            {% if obj.ciudad %}<li><p><span class="glyphicon glyphicon-globe" style="width:50px;"></span>{{ obj.ciudad }}</p></li>{% endif %}
                          </ul>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >{% if obj.fecha_Nacimiento %}Fecha de Nacimiento: {{ obj.fecha_Nacimiento }}{% endif %}</div>
                          <hr>
                          <div class="col-sm-12 col-xs-12 tital " >Se unió: {{ obj.date_joined }}</div>
                          
                      </div>
                    </div>
                    <hr>
                    <p class="text-center"><a href="{% url 'users:userupdateobservatorio' id=obj.id %}" class="btn btn-primary" role="button">Modificar Datos Administrador</a>
                    <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a> </p>
                </div>
        {% endif %}
    {% endfor %}
{% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if objects_list.has_previous %}
                <a href="?page=1 {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; primero</a>
                <a href="?page={{ objects_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">anterior</a>
            {% endif %}
    
            <span class="current">
                Usuario {{ objects_list.number }} de {{ objects_list.paginator.num_pages }}
            </span>
    
            {% if objects_list.has_next %}
                <a href="?page={{ objects_list.next_page_number }} {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">siguiente</a>
                <a href="?page={{ objects_list.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">último &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

src/templates/user_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title%}{{ title }} | {{ block.super }} {% endblock %}

{% block content %}
<div class="col-sm-10 col-sm-offset-1" >
    <form method="POST" action="" enctype="multipart/form-data" >{% csrf_token %}
        {{ form|crispy }}
        <br/>
        <p class="text-center"><input class="btn btn-primary" type="submit" value="Guardar Cambios">
        <a href="{% url 'portal:inicio' %}" class="btn btn-primary" role="button">Cancelar</a></p>
    </form>
</div>
{% endblock %}